import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import CurrentSongProvider from "@/stores/currentSongContext";
import QueueSongProvider from "@/stores/songQueueContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
   title: "Next MP3",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <CurrentSongProvider>
            <QueueSongProvider>
               <body
                  className={`${inter.className} bg-amber-200 min-h-screen`}
               >
                  {children}
               </body>
            </QueueSongProvider>
         </CurrentSongProvider>
      </html>
   );
}
